name: Test (Deno)

on: [push]

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Lint
        run: deno lint --unstable

  format:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Format
        run: |
          deno fmt --check

  # test:
  #   runs-on: ubuntu-20.04
  #
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: denolib/setup-deno@v2
  #       with:
  #         deno-version: v1.x
  #     - name: Test
  #       run: |
  #         deno test
